// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Only load dotenv in development/local environments
if (process.env.NODE_ENV !== "production") {
    try {
      require("dotenv/config");
    } catch {
      // dotenv not available or .env file doesn't exist - that's okay in production
    }
  }
  import { defineConfig } from "prisma/config";
  
  export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
      path: "prisma/migrations",
    },
    datasource: {
      url: process.env["DATABASE_URL"] as string,
    },
  });